#syntax=docker/dockerfile:1

FROM ubuntu:24.04 AS base

ARG TARGETARCH
ARG TARGETPLATFORM
ARG TARGETOS
ARG BUILDARCH
ARG BUILDPLATFORM
ARG BUILDOS
ARG ARCH=${TARGETARCH/arm64/aarch64}
ARG ARCH=${ARCH/amd64/x64}

RUN echo "ARCH=${ARCH}" \
&& echo "TARGETOS=${TARGETOS}" \
&& echo "TARGETARCH=${TARGETARCH}" \
&& echo "TARGETPLATFORM=${TARGETPLATFORM}" \
&& echo "BUILDOS=${BUILDOS}" \
&& echo "BUILDARCH=${BUILDARCH}" \
&& echo "BUILDPLATFORM=${BUILDPLATFORM}"
