name: Publish Docker image
on:
  workflow_dispatch:
    inputs:
      runson:
        required: true
        default: 'ubuntu-latest'    
      arg1:
        required: true
        default: 'db'
      arg2:
        required: true
        default: 'node'
      arg3:
        default: ''
      arg4:
        default: ''
      arg5:
        default: ''
      src:
        required: true
        default: ''        
  push:
    tags:
      - '*'

# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    # runs-on: ubuntu-latest
    runs-on: "${{ inputs.runson }}"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # - name: Check out the repo
      #   uses: actions/checkout@v4 
      #   with:
      #     repository: ${{ secrets.DH_USERNAME }}/docker-dev
      #     token: ${{ secrets.GH_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          SOURCE_FILE: ${{ inputs.src }}
        run: |
          ./build.sh src ${{ inputs.arg1 }} ${{ inputs.arg2 }} \
          ${{ inputs.arg3 }} ${{ inputs.arg4 }} ${{ inputs.arg5 }}
