name: Publish Docker image
on:
  workflow_dispatch:
    inputs:
      runson:
        required: true
        default: 'ubuntu-latest'    
      arg1:
        required: true
        default: 'db'
      arg2:
        required: true
        default: 'node'
      arg3:
        default: ''
      arg4:
        default: ''
      arg5:
        default: ''
  push:
    tags:
      - '*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    # runs-on: ubuntu-latest
    runs-on: "${{ inputs.runson }}"
    steps:
      # - name: Check out the repo
      #   uses: actions/checkout@v4

      - name: Check out the repo
        uses: actions/checkout@v4 
        with:
          repository: ${{ secrets.DH_USERNAME }}/docker-dev
          token: ${{ secrets.GH_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        run: |
          ./build-ci.sh ${{ inputs.arg1 }} ${{ inputs.arg2 }} \
          ${{ inputs.arg3 }} ${{ inputs.arg4 }} ${{ inputs.arg5 }}
