name: Build Flutter App
on:
  workflow_dispatch:
    inputs:
      runson:
        required: true
        default: 'ubuntu-latest'    
      arg1:
        required: true
        default: 'ci'
      arg2:
        default: ''
      arg3:
        default: ''
      arg4:
        default: ''
      arg5:
        default: ''
      src:
        required: true
        default: ''        
  push:
    tags:
      - '*'

# permission can be added at the job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build_flutter_apk:
    name: Build Flutter APK
    runs-on: "${{ inputs.runson }}"
    container:
      image: apollo14lm/flutter:ci
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build and push
        env:
          BUCKET_PROJECT: ${{ secrets.BUCKET_PROJECT }}
          BUCKET_ARTIFACT: ${{ secrets.BUCKET_ARTIFACT }}
          SOURCE_FILE: ${{ inputs.src }}
        run: |
          # Fix git dubious ownership error for Flutter SDK
          git config --global --add safe.directory /opt/flutter
          
          ./build.sh src ${{ inputs.arg1 }} ${{ inputs.arg2 }} \
          ${{ inputs.arg3 }} ${{ inputs.arg4 }} ${{ inputs.arg5 }}
